# Generated by Django 4.0.1 on 2022-01-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=200)),
                ('number', models.IntegerField(max_length=200)),
                ('pokemon_name', models.TextField(max_length=200)),
            ],
        ),
    ]
