# Generated by Django 4.0.1 on 2022-01-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_pokemon_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='featured_image',
            field=models.ImageField(blank=True, default='Pokemon-logo-tumb.jpg', null=True, upload_to=''),
        ),
    ]
